export const mockExpenseLedgerData = [
  {
    date: "01/05/2024",
    category: "Water & Electric Bill",
    description: "Expenses for water supply and electricity consumption of the school.",
    department: "Admin",
    priority: "High",
    amount: "P 35,000",
    status: "Paid",
    icon: "bolt",
    iconClass: "water-electric",
  },
  {
    date: "01/12/2024",
    category: "Maintenance",
    description: "Costs for repairs, upkeep, and regular maintenance of school facilities.",
    department: "Facilities",
    priority: "Medium",
    amount: "P 12,000",
    status: "Pending",
    icon: "wrench",
    iconClass: "maintenance",
  },
  {
    date: "01/15/2024",
    category: "Supplies Expenses",
    description: "Consumable items used daily such as bond paper, ink, pens, and cleaning materials.",
    department: "Admin",
    priority: "Low",
    amount: "P 5,500",
    status: "Paid",
    icon: "supplies",
    iconClass: "supplies",
  },
  {
    date: "01/18/2024",
    category: "Security and Janitorial Services",
    description: "Payments for security personnel and cleaning staff services.",
    department: "Security",
    priority: "High",
    amount: "P 20,000",
    status: "Paid",
    icon: "security",
    iconClass: "security",
  },
  {
    date: "01/25/2024",
    category: "Equipment Expenses",
    description: "Purchases or repairs of school equipment like computers, printers, and projectors.",
    department: "IT Dept",
    priority: "High",
    amount: "P 50,000",
    status: "Unpaid",
    icon: "computer",
    iconClass: "equipment",
  },
  {
    date: "01/28/2024",
    category: "Development Fund",
    description: "Budget allocated for future school improvements and projects.",
    department: "Student Affairs",
    priority: "Medium",
    amount: "P 15,000",
    status: "Paid",
    icon: "fund",
    iconClass: "development",
  },
  {
    date: "02/02/2024",
    category: "Fire Safety Equipment",
    description: "Costs for fire extinguishers, alarms, and other safety devices.",
    department: "Admin",
    priority: "Low",
    amount: "P 8,000",
    status: "Paid",
    icon: "shield",
    iconClass: "fire-safety",
  },
  {
    date: "02/05/2024",
    category: "Internet Bill",
    description: "Monthly payment for internet connectivity used for school operations.",
    department: "IT Dept",
    priority: "High",
    amount: "P 18,000",
    status: "Pending",
    icon: "wifi",
    iconClass: "internet",
  },
  {
    date: "02/10/2024",
    category: "Utilities",
    description: "General utility costs such as gas, waste disposal, and other essential services.",
    department: "Admin",
    priority: "Medium",
    amount: "P 9,500",
    status: "Paid",
    icon: "utilities",
    iconClass: "utilities",
  },
  {
    date: "02/14/2024",
    category: "Electrical Materials",
    description: "Expenses for electrical supplies such as wires, bulbs, switches, and outlets.",
    department: "Facilities",
    priority: "Medium",
    amount: "P 7,200",
    status: "Paid",
    icon: "electrical",
    iconClass: "electrical",
  },
  {
    date: "02/20/2024",
    category: "Replacement of Lost or Damaged Items",
    description: "Expenses for replacing or repairing lost, broken, or damaged school property.",
    department: "Property Office",
    priority: "High",
    amount: "P 11,800",
    status: "Pending",
    icon: "replace",
    iconClass: "replacement",
  },
  {
    date: "02/26/2024",
    category: "Transportation Expenses",
    description: "Costs related to transportation such as fuel, vehicle maintenance, service vehicles, and travel expenses for school activities.",
    department: "Logistics",
    priority: "Medium",
    amount: "P 13,400",
    status: "Paid",
    icon: "transport",
    iconClass: "transportation",
  },
];
